[tasks.dev]
script = ["rustup component add clippy", "cargo install cargo-readme"]

[tasks.eval]
dependencies = ["check-format", "check-readme", "deny-clippy", "test-verbose"]

[tasks.readme]
script = ["cargo readme > README.md"]

[config]
on_error_task = "delete-temp-readme"

[tasks.deny-clippy]
script = ["cargo clippy -- -D warnings"]

[tasks.check-readme]
dependencies = ["compare-readme"]
run_task = "delete-temp-readme"

[tasks.compare-readme]
script = ["cargo readme > r", "fc r README.md"]

[tasks.delete-temp-readme]
script = ["if exist r rm r"]
