[tasks.dev]
script = ["cargo install cargo-readme"]

[tasks.eval]
dependencies = ["check-readme"]

[tasks.fix]
dependencies = ["fix-readme"]

[config]
on_error_task = "delete-temp-readme"

[tasks.fix-readme]
script = ["cargo readme > README.md"]

[tasks.check-readme]
dependencies = ["compare-readme"]
run_task = "delete-temp-readme"

[tasks.compare-readme]
script = ["cargo readme > r", "fc r README.md"]

[tasks.delete-temp-readme]
script = ["if exist r rm r"]
